name: trigger-docs
on:
  workflow_dispatch:
     inputs:
      target:
        description: 'Ù‹Workflow 2 which will be triggered'
        required: true
        default: 'build'

      target_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: ':userName'

      target_repo_github:
        description: 'repo-name'
        required: true
        default: ':repoName' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          curl -X POST https://api.github.com/repos/:userName/:repoName/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTIONS_KEY }} \
          --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - uses: actions/checkout@v3
